// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57DAOccwmiDjH5hg-eVQ9m67HbrYRZS0',
    appId: '1:177925156640:web:cd871949d64c9c841af145',
    messagingSenderId: '177925156640',
    projectId: 'velotolouse-60964',
    authDomain: 'velotolouse-60964.firebaseapp.com',
    storageBucket: 'velotolouse-60964.firebasestorage.app',
    measurementId: 'G-LVCXEZV6BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuI9VJKFYQ-f1LWri0ec4W5FC5H2mFe7I',
    appId: '1:177925156640:android:85c0252eb4a1ed961af145',
    messagingSenderId: '177925156640',
    projectId: 'velotolouse-60964',
    storageBucket: 'velotolouse-60964.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArOAFhOjT2woeQ_SfYykw-_GrGLqkCpcA',
    appId: '1:177925156640:ios:443ed5418d367f981af145',
    messagingSenderId: '177925156640',
    projectId: 'velotolouse-60964',
    storageBucket: 'velotolouse-60964.firebasestorage.app',
    iosBundleId: 'com.example.velotolouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArOAFhOjT2woeQ_SfYykw-_GrGLqkCpcA',
    appId: '1:177925156640:ios:443ed5418d367f981af145',
    messagingSenderId: '177925156640',
    projectId: 'velotolouse-60964',
    storageBucket: 'velotolouse-60964.firebasestorage.app',
    iosBundleId: 'com.example.velotolouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB57DAOccwmiDjH5hg-eVQ9m67HbrYRZS0',
    appId: '1:177925156640:web:c60b463436a940301af145',
    messagingSenderId: '177925156640',
    projectId: 'velotolouse-60964',
    authDomain: 'velotolouse-60964.firebaseapp.com',
    storageBucket: 'velotolouse-60964.firebasestorage.app',
    measurementId: 'G-XLXXBH1QDX',
  );
}
